on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/5e69bd7d79df0cf7dbb8f99c1c7c5e40
          gist_title: 6-ADC-set-Point-CCS-4550.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F4550/ADC Set Point.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/d62989b36ff6d4c32d1ce6751fb73597
          gist_title: 6-ADC-Set-Point-CCS.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F45K50/ADC Set Point.c
          file_encoding: WINDOWS-1252